management:
  health:
    diskspace:
      enabled: "true"
    default:
      enabled: "true"
    db:
      enabled: "true"
  servlet:
    context-path: /manage
spa:
  default-file: /dist/index.html
spring:
  web:
    resources:
      static-locations: classpath:/dist/
      add-mappings: "false"
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    hikari:
#      username: ssafy
#      password: ssafy
#    url: jdbc:mariadb://localhost:3306/daengdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      username: daeng
      password: daengpotato
    url: jdbc:mariadb://j9a103.p.ssafy.io:3324/daengdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
  data:
    web:
      pageable:
        one-indexed-parameters: "true"
  mvc:
    throw-exception-if-no-handler-found: "true"
  devtools:
    livereload:
      enabled: "true"
  redis:
    host: 127.0.0.1
    port: 6379
logging:
  level:
    org:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.springframework.boot: DEBUG
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
      apache:
        tiles: INFO
    root: INFO
    com:
      samsung:
        security: DEBUG
  file:
    name: ./ssafy-web.log
server:
  servlet:
    encoding:
      enabled: "true"
      force: "true"
      charset: UTF-8
    contextPath: /api
  address: localhost
  port: 9001
  compression:
    enabled: "true"
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
build:
  date: "@build.date@"
jwt:
  expiration: '1296000000'
  cookieName: daengCookie
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
springfox:
  documentation:
    swagger:
      use-model-v3: 'false'