management:
  health:
    diskspace:
      enabled: "true"
    default:
      enabled: "true"
    db:
      enabled: "true"
  servlet:
    context-path: /manage
spa:
  default-file: /dist/index.html

kakao:
  rest-api-key: bbc1c00867e7b19dabe76d4afd823b22
  redirect-uri: https://j9a103.p.ssafy.io/kakao
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 594259902249-6gubj4rdq3lko07198hjm2cblj3n1atk.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://j9a103.p.ssafy.io/
            scope:
              - openid
              - email
              - profile

        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
          google:
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  web:
    resources:
      static-locations: classpath:/dist/
      add-mappings: "false"
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
      init:
        mode: always
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      username: daeng
      password: daengpotato
    url: jdbc:mariadb://j9a103.p.ssafy.io:3324/daengdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
  data:
    web:
      pageable:
        one-indexed-parameters: "true"
  mvc:
    throw-exception-if-no-handler-found: "true"
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    livereload:
      enabled: "true"
  redis:
    host: j9a103.p.ssafy.io
    port: 6379
    password: ssafy
logging:
  level:
    org:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.springframework.boot: DEBUG
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
      apache:
        tiles: INFO
    root: INFO
    com:
      samsung:
        security: DEBUG
  file:
    name: ./ssafy-web.log
server:
  servlet:
    encoding:
      enabled: "true"
      force: "true"
      charset: UTF-8
    contextPath: /api
  address: 0.0.0.0
  port: 8200
  compression:
    enabled: "true"
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
build:
  date: "@build.date@"
jwt:
  expiration: '1296000000'
  cookieName: daengCookie
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
springfox:
  documentation:
    swagger:
      use-model-v3: 'false'
cloud:
  aws:
    s3:
      bucket: daengdaeng-bucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIAZPGUZGK2ELTIE55G
      secret-key: 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
